/*
RGB reference table

red			#FF0000
orange		#FF7F00
yellow		#FFFF00
green		#00FF00
blue		#0000FF
violet		#8B00FF

black		#000000
gray		#808080
lightgray	#D3D3D3
white		#FFFFFF
*/

/*
Editable values
*/

//Drawing configuration variables
var RAINBOW_COLORS = ["#FF0000", "#FF7F00", "#FFFF00", "#00FF00", "#0000FF", "#8B00FF"];
var BLACK_TO_GRAYS_TO_WHITE_COLORS = ["#000000", "#808080", "#D3D3D3", "#FFFFFF"];
var DRAWING_COLOR = BLACK_TO_GRAYS_TO_WHITE_COLORS[0];
var DRAWING_WIDTH = 4;
var MIN_DRAWING_WIDTH = 1;
var MAX_DRAWING_WIDTH = 72;
//-------------------------------

//Locale configuration variables
var LANGUAGE = "pt_BR";
//------------------------------

//Menu configuration variables
var CANVAS_MENU = 0;
var OBJECT_MENU = 1;
var MORPHISM_MENU = 2;
var MULTIPLE_MENU = 2;

var CREATE_OBJECT = 0;
var SELECT_ALL = 1;
var SELECT_OBJECTS = 2;
var SELECT_MORPHISMS = 3;
var SELECT_ENDOMORPHISMS = 4;
var CREATE_MORPHISM_TO = 5;
var CREATE_MORPHISM_FROM = 6;
var READ_OBJECT = 7;
var UPDATE_OBJECT = 8;
var DELETE_OBJECT = 9;
var SELECT_OBJECT = 10;
var CHANGE_TYPE = 11;
var READ_MORPHISM = 12;
var UPDATE_MORPHISM = 13;
var DELETE_MORPHISM = 14;
var SELECT_MORPHISM = 15;
var CUT_SELECTED = 16;
var COPY_SELECTED = 17;
var DUPLICATE_MORPHISM = 18;
var DUPLICATE_OBJECT_AND_MORPHISM_WITH_SAME_SOURCE = 19;
var DUPLICATE_OBJECT_AND_MORPHISM_WITH_SAME_TARGET = 20;

var SHORTCUT_CREATE_OBJECT = 'C';
var SHORTCUT_SELECT_ALL = 'A';
var SHORTCUT_SELECT_OBJECTS = 'O';
var SHORTCUT_SELECT_MORPHISMS = 'M';
var SHORTCUT_SELECT_ENDOMORPHISMS = 'E';
var SHORTCUT_CREATE_MORPHISM_TO = 'T';
var SHORTCUT_CREATE_MORPHISM_FROM = 'F';
var SHORTCUT_READ_OBJECT = 'R';
var SHORTCUT_UPDATE_OBJECT = 'U';
var SHORTCUT_DELETE_OBJECT = 'D';
var SHORTCUT_SELECT_OBJECT = 'S';
var SHORTCUT_CHANGE_TYPE = 'C';
var SHORTCUT_READ_MORPHISM = 'R';
var SHORTCUT_UPDATE_MORPHISM = 'U';
var SHORTCUT_DELETE_MORPHISM = 'D';
var SHORTCUT_SELECT_MORPHISM = 'S';
var SHORTCUT_CUT_SELECTED = 'U';
var SHORTCUT_COPY_SELECTED = 'O';
var SHORTCUT_DUPLICATE_MORPHISM = 'D';
var SHORTCUT_DUPLICATE_OBJECT_AND_MORPHISM_WITH_SAME_SOURCE = 'S';
var SHORTCUT_DUPLICATE_OBJECT_AND_MORPHISM_WITH_SAME_TARGET = 'T';

var MENU_FADE_IN_DURATION = 200;

var DEFAULT_CANVAS_INPUT_COLOR = "#F9F9F9";
var DEFAULT_OBJECT_INPUT_COLOR = "#F08080";
var DEFAULT_MORPHISM_INPUT_COLOR = "#9999FF";

var DEFAULT_MORPHISM_INPUT_DROPDOWN_LIST_BACKGROUND_COLOR = "#FFFFFF";
var DEFAULT_MORPHISM_INPUT_DROPDOWN_LIST_COLOR = "#000000";
var SELECTED_MORPHISM_INPUT_DROPDOWN_LIST_BACKGROUND_COLOR = "#0000FF";
var SELECTED_MORPHISM_INPUT_DROPDOWN_LIST_COLOR = "#FFFFFF";
//----------------------------

//TSV configuration variables
var TSV_COLOR = "#808080";
var TSV_INPUT_COLOR = "#F9F9F9";
//---------------------------

//Mouse configuration variables
var DOUBLE_CLICK_TOLERANCE = 200;
//-----------------------------

//Keyboard configuration variables
var SHORTCUT_MORPHISM_TYPE_MORPHISM = 'Q';
var SHORTCUT_MORPHISM_TYPE_MONOMORPHISM = 'W';
var SHORTCUT_MORPHISM_TYPE_EPIMORPHISM = 'E';
var SHORTCUT_MORPHISM_TYPE_MONOEPIMORPHISM = 'R';
var SHORTCUT_MORPHISM_TYPE_ISOMORPHISM = 'T';
//--------------------------------

//View configuration variables
var DEFAULT_ENDOMORPHISM_COLOR = "#0000FF";
var DEFAULT_ENDOMORPHISM_WIDTH = 4;
var DEFAULT_ENDOMORPHISM_LABEL_FONT_NAME = "sans-serif";
var DEFAULT_ENDOMORPHISM_LABEL_FONT_SIZE = "12px";
var DEFAULT_ENDOMORPHISM_LABEL_COLOR = "#000000";

var DEFAULT_ID_ENDOMORPHISM_COLOR = "#00FF00";
var DEFAULT_ID_ENDOMORPHISM_WIDTH = 4;
var DEFAULT_ID_ENDOMORPHISM_LABEL_FONT_NAME = "sans-serif";
var DEFAULT_ID_ENDOMORPHISM_LABEL_FONT_SIZE = "12px";
var DEFAULT_ID_ENDOMORPHISM_LABEL_COLOR = "#000000";

var DEFAULT_CIRCLE_COLOR = "#FF0000";
var DEFAULT_CIRCLE_RADIUS = 30;
var DEFAULT_CIRCLE_LABEL_FONT_NAME = "sans-serif";
var DEFAULT_CIRCLE_LABEL_FONT_SIZE = "20px";
var DEFAULT_CIRCLE_LABEL_COLOR = "#000000";

var DEFAULT_HANDLE_RADIUS = 10;
var DEFAULT_HANDLE_COLOR = "#FF0000";

var DEFAULT_ID_HANDLE_RADIUS = 10;
var DEFAULT_ID_HANDLE_COLOR = "#FFFF00";

var DEFAULT_CURVE_COLOR = "#0000FF";
var DEFAULT_CURVE_WIDTH = 4;
var DEFAULT_CURVE_LABEL_FONT_NAME = "sans-serif";
var DEFAULT_CURVE_LABEL_FONT_SIZE = "12px";
var DEFAULT_CURVE_LABEL_COLOR = "#000000";

var SELECTED_ENDOMORPHISM_COLOR = "#00FF00";
var SELECTED_ENDOMORPHISM_WIDTH = 4;
var SELECTED_ENDOMORPHISM_LABEL_FONT_NAME = "sans-serif";
var SELECTED_ENDOMORPHISM_LABEL_FONT_SIZE = "12px";
var SELECTED_ENDOMORPHISM_LABEL_COLOR = "#000000";

var SELECTED_ID_ENDOMORPHISM_COLOR = "#0000FF";
var SELECTED_ID_ENDOMORPHISM_WIDTH = 4;
var SELECTED_ID_ENDOMORPHISM_LABEL_FONT_NAME = "sans-serif";
var SELECTED_ID_ENDOMORPHISM_LABEL_FONT_SIZE = "12px";
var SELECTED_ID_ENDOMORPHISM_LABEL_COLOR = "#000000";

var SELECTED_CIRCLE_COLOR = "#0000FF";
var SELECTED_CIRCLE_RADIUS = 30;
var SELECTED_CIRCLE_LABEL_FONT_NAME = "sans-serif";
var SELECTED_CIRCLE_LABEL_FONT_SIZE = "20px";
var SELECTED_CIRCLE_LABEL_COLOR = "#000000";

var SELECTED_HANDLE_RADIUS = 10;
var SELECTED_HANDLE_COLOR = "#0000FF";

var SELECTED_ID_HANDLE_RADIUS = 10;
var SELECTED_ID_HANDLE_COLOR = "#00FFFF";

var SELECTED_CURVE_COLOR = "#00FF00";
var SELECTED_CURVE_WIDTH = 4;
var SELECTED_CURVE_LABEL_FONT_NAME = "sans-serif";
var SELECTED_CURVE_LABEL_FONT_SIZE = "12px";
var SELECTED_CURVE_LABEL_COLOR = "#000000";

var RECT_STROKE = "#0000FF";
var RECT_FILL = "#ADD8E6";//lightblue
var RECT_WIDTH = 2;

var ARROW_HEAD_ANGLE = 45;
var ARROW_HEAD_LENGTH = 20;

var BEZIER_MULTIPLIER = 1/12;
var BEZIER_POINTS = 1000;
var BEZIER_PRECISION = 2000/BEZIER_POINTS;

var GRID_VISIBLE = true;
var GRID_FONT_NAME = "sans-serif";
var GRID_FONT_SIZE = "8px";
var GRID_COLOR = "#000000";
var GRID_WIDTH = 1;
var GRID_OPACITY = 0.4;
var LIMIT_VISIBLE = true;
var LIMIT = 2 * SELECTED_CIRCLE_RADIUS + SELECTED_HANDLE_RADIUS;
//----------------------------

//Internal pages opening configuration variables
var OPEN_HELP_PAGE_ON_STARTUP = true;
//----------------------------------------------

//Cut, copy and paste configuration variables
var PASTE_ANGLE = 315;
//-------------------------------------------

//Collision configuration variables
var CHECK_COLLISION_ON_MOUSE_MOVE = false;
//----------------------------------------------
